### ISSUE TITLE
在管理后台增加了记录，但未同步到配置文件中，请问题是什么原因？

### ISSUE THREAD

**Issue by drings-liu** [zekeli/dns-manager#4]
如题，已配置好管理后台，脚本也部署完未报错，在后台增加zone、A记录后，未及时同步到
脚本中未检测到etcd中变化。请问是哪里原因造成

**Comment by jackjiali** [comment]
> 如题，已配置好管理后台，脚本也部署完未报错，在后台增加zone、A记录后，未及时同步到
> 脚本中未检测到etcd中变化。请问是哪里原因造成

要不你试试部署我这个项目吧，peb-dns，两个代码基本一样的，peb-dns部署我都验证过了，应该没啥问题。
这个dns-manager部署我还没验证过，如果后端能找到报错日志，也可以发我下，好久没关心这个项目了，很多都忘记了

**Comment by drings-liu** [comment]
嗯，部署peb-dns正常了。
不过有很多功能需要自己去琢磨。
